apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-config
  labels:
    app: boundary
data:
  boundary.hcl: |
    disable_mlock = true

    controller {
      name        = "env://POD_NAME"
      description = "Boundary controller"

      database {
        url = "env://POSTGRES_CONNECTION"
      }

      public_cluster_addr = "env://CONTROLLER_CLUSTER_SERVICE_HOST"
    }

    # Public API listener configuration blocks
    listener "tcp" {
      address     = "0.0.0.0:9200"
      purpose     = "api"
      tls_disable = true
    }

    # Data-plane listener configuration block (used for worker coordination)
    listener "tcp" {
      address     = "0.0.0.0:9201"
      purpose     = "cluster"
      tls_disable = true
    }

    kms "aead" {
      purpose   = "root"
      aead_type = "aes-gcm"
      key       = "sP1fnF5Xz85RrXyELHFeZg9Ad2qt4Z4bgNHVGtD6ung="
      key_id    = "global_root"
    }
    
    kms "aead" {
      purpose   = "worker-auth"
      aead_type = "aes-gcm"
      key       = "8fZBjCUfN0TzjEGLQldGY4+iE9AkOvCfjh7+p0GtRBQ="
      key_id    = "global_worker-auth"
    }

    kms "aead" {
      purpose   = "recovery"
      aead_type = "aes-gcm"
      key       = "8fZBjCUfN0TzjEGLQldGY4+iE9AkOvCfjh7+p0GtRBQ="
      key_id    = "global_recovery"
    }